[time-to-sleep]
mon = [{ after = '22:00', before = '4:00' }]
tue = [{ after = '22:00', before = '4:00' }]
wed = [{ after = '22:00', before = '4:00' }]
thu = [{ after = '22:00', before = '4:00' }]
fri = [{ after = '22:00', before = '4:00' }]
sat = [{ after = '22:00', before = '4:00' }]
sun = [{ after = '22:00', before = '4:00' }]

[not-social-networks]
mon = [{ after = '6:00', before = '16:00' }]
tue = [{ after = '6:00', before = '16:00' }]
wed = [{ after = '6:00', before = '16:00' }]
thu = [{ after = '6:00', before = '16:00' }]
fri = [{ after = '6:00', before = '16:00' }]
sat = [{ after = '6:00', before = '16:00' }]
sun = [{ after = '6:00', before = '16:00' }]
